# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db-integration-tests:
    image: postgres:14
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
  db-dev:
    image: postgres:14
    restart: always
    container_name: dev
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: dev