# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db-integration-tests:
    image: postgres:14
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
  db-dev:
    image: postgres:14
    restart: always
    container_name: dev
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: dev
    volumes:
      - ./data:/var/lib/postgresql/data
  api:
    container_name: api-container
    build: .
    image: agenda-beach
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/agenda-beach/dist
      - ./package.json:/usr/src/agenda-beach/package.json
    ports: 
      - "3000:3000"
      - "9222:9222"
    links:
      - db-dev